// Code generated by linux/mkall.go generatePtraceRegSet("loongarch64"). DO NOT EDIT.

package unix

import "unsafe"

// PtraceGetRegSetLoongarch64 fetches the registers used by loongarch64 binaries.
func PtraceGetRegSetLoongarch64(pid, addr int, regsout *PtraceRegsLoongarch64) error {
	iovec := Iovec{(*byte)(unsafe.Pointer(regsout)), uint64(unsafe.Sizeof(*regsout))}
	return ptrace(PTRACE_GETREGSET, pid, uintptr(addr), uintptr(unsafe.Pointer(&iovec)))
}

// PtraceSetRegSetLoongarch64 sets the registers used by loongarch64 binaries.
func PtraceSetRegSetLoongarch64(pid, addr int, regs *PtraceRegsLoongarch64) error {
	iovec := Iovec{(*byte)(unsafe.Pointer(regs)), uint64(unsafe.Sizeof(*regs))}
	return ptrace(PTRACE_SETREGSET, pid, uintptr(addr), uintptr(unsafe.Pointer(&iovec)))
}

// PtraceRegsLoongarch is the registers used by loongarch binaries.
type PtraceRegsLoongarch struct {
	Uregs [18]uint32
}

// PtraceGetRegsLoongarch fetches the registers used by loongarch binaries.
func PtraceGetRegsLoongarch(pid int, regsout *PtraceRegsLoongarch) error {
	return ptrace(PTRACE_GETREGS, pid, 0, uintptr(unsafe.Pointer(regsout)))
}

// PtraceSetRegsLoongarch sets the registers used by loongarch binaries.
func PtraceSetRegsLoongarch(pid int, regs *PtraceRegsLoongarch) error {
	return ptrace(PTRACE_SETREGS, pid, 0, uintptr(unsafe.Pointer(regs)))
}

// PtraceRegsLoongarch64 is the registers used by loongarch64 binaries.
type PtraceRegsLoongarch64 struct {
	Regs   [31]uint64
	Sp     uint64
	Pc     uint64
	Pstate uint64
}

// PtraceGetRegsLoongarch64 fetches the registers used by loongarch64 binaries.
func PtraceGetRegsLoongarch64(pid int, regsout *PtraceRegsLoongarch64) error {
	return ptrace(PTRACE_GETREGS, pid, 0, uintptr(unsafe.Pointer(regsout)))
}

// PtraceSetRegsLoongarch64 sets the registers used by loongarch64 binaries.
func PtraceSetRegsLoongarch64(pid int, regs *PtraceRegsLoongarch64) error {
	return ptrace(PTRACE_SETREGS, pid, 0, uintptr(unsafe.Pointer(regs)))
}
